modelname: bert_resnet_weight
lr: 0.000001
lr_finetune: 0.00001
lr_downstream: 0.002
batch_size: 12
epochs: 100
patience: 4
device: cpu
log_dir: logs

resnet: 50

use_text: 1
use_image: 1

train_small: 1
train: 1
